### ISSUE TITLE
Null Rechnung erstellen schlägt fehlt.

### ISSUE THREAD

**Issue by KurzGedanke** [d-koppenhagen/latex-rechnung#6]
Ich wollte eine Null Rechnung erstellen.

Mein Hauptbetrag war 2.79€ und diesen wollte ich mit 2.79€ rabattieren. Allerdings rabattierte es in der pdf selber nur 2.78€ und es bleibt 0.01€ übrig. Wenn ich es für 2.80€ rabattieren bleibt -0.01€ übrig.

**Comment by antonbrall** [comment]
Interessant, das scheint immer nur zu passiern, wenn die Zahl nach dem Komma .90 ist, da ist es dann aber egal, was vor dem Komma steht

**Comment by antonbrall** [comment]
fixed by #13
